export loadInfo from './loadInfo'
export loadAuth from './loadAuth'
export login from './login'
export logout from './logout'
export news from './news'
export * as widget from './widget/index'
export * as survey from './survey/index'
